trigger:
- main

pool: Default

steps:
- script: |
    echo "Fortify SCA version:"
    sourceanalyzer -v
    echo "Fortify SCA location in PATH:"
    which sourceanalyzer
  displayName: 'Check Fortify SCA version and path'
  
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    buildToolOptions: 'gradle clean build'
    fortifyBuildId: 'testGradle'
    scaVerbose: true
    scaDebug: true
    fortifyScanType: 'ScanCentralScan'
    scanCentralFortifyServerName: 'SSC Connection'
    scanCentralRunFortifyUpload: true
    scanCentralFortifyApplicationIdentifierType: 'byId'
    scanCentralFortifyApplicationVersionId: '10004'
    taskResultForBuildFailureCriteria: 'FAIL'