trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    buildToolOptions: 'gradle clean build'
    fortifyBuildId: 'testGradle'
    scaVerbose: true
    scaDebug: true
    fortifyScanType: 'ScanCentralScan'
    scanCentralFortifyServerName: 'SSC Connection'
    scanCentralRunFortifyUpload: true
    scanCentralFortifyApplicationIdentifierType: 'byId'
    scanCentralFortifyApplicationVersionId: '10004'
    taskResultForBuildFailureCriteria: 'FAIL'